import{analyzeFit,analyzeSamples}from'./fit-analysis.js';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const text=(el,name)=>{const n=[...el.getElementsByTagName('*')].find(x=>x.localName===name);return n?.textContent?.trim()||null};
const children=(root,name)=>[...root.getElementsByTagName('*')].filter(x=>x.localName===name);
function toMs(v){const n=new Date(v).getTime();return Number.isFinite(n)?n:null}
function normalize(records,label){records=records.filter(r=>r.ms!=null).sort((a,b)=>a.ms-b.ms);if(!records.length)throw new Error(`El ${label} no contiene puntos con tiempo.`);const t0=records[0].ms;const samples=records.map((r,i)=>({tSec:(r.ms-t0)/1000,dt:i?Math.max(0,Math.min(8,(r.ms-records[i-1].ms)/1000)):0,lat:r.lat,lon:r.lon,speedKmh:r.speedKmh,distance:r.distance,hr:r.hr,cadence:r.cadence}));return{samples,t0}}
function parseXml(xml,label){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error(`No se pudo leer el archivo ${label}.`);return doc}
function parseGpx(xml){const doc=parseXml(xml,'GPX'),pts=children(doc,'trkpt').map(p=>{const speed=num(text(p,'speed'));return{ms:toMs(text(p,'time')),lat:num(p.getAttribute('lat')),lon:num(p.getAttribute('lon')),speedKmh:speed==null?null:speed*3.6,distance:null,hr:num(text(p,'hr')),cadence:num(text(p,'cad')??text(p,'cadence'))}});return normalize(pts,'GPX')}
function parseTcx(xml){const doc=parseXml(xml,'TCX'),pts=children(doc,'Trackpoint').map(p=>{const pos=children(p,'Position')[0],lat=pos?num(text(pos,'LatitudeDegrees')):null,lon=pos?num(text(pos,'LongitudeDegrees')):null;let speed=num(text(p,'Speed'));if(speed!=null)speed*=3.6;return{ms:toMs(text(p,'Time')),lat,lon,speedKmh:speed,distance:num(text(p,'DistanceMeters')),hr:num(text(p,'Value')),cadence:num(text(p,'Cadence'))}});return normalize(pts,'TCX')}
export function detectActivityFormat(file){const n=String(file?.name||'').toLowerCase();if(n.endsWith('.fit'))return'fit';if(n.endsWith('.gpx'))return'gpx';if(n.endsWith('.tcx'))return'tcx';return null}
export async function analyzeActivityFile(file,options={}){const format=detectActivityFormat(file);if(!format)throw new Error('Formato no compatible. Usa FIT, GPX o TCX.');if(format==='fit'){const a=await analyzeFit(await file.arrayBuffer(),options);a.sourceFormat='fit';return a}const xml=await file.text(),parsed=format==='gpx'?parseGpx(xml):parseTcx(xml),a=analyzeSamples(parsed.samples,parsed.t0,options);a.sourceFormat=format;return a}
