import{buildFatigueProfile}from'./fatigue-profile.js';
const finite=v=>Number.isFinite(Number(v));
const pct=v=>finite(v)?Math.round(Number(v)*100):null;
const fmtClock=sec=>{const n=Math.max(0,Math.round(Number(sec)||0)),m=Math.floor(n/60),s=n%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')};
const fmt1=v=>finite(v)?Number(v).toFixed(1):'—';

export function fatiguePanelHtml(speed,durationS){
  const f=buildFatigueProfile(speed,durationS);if(!f.available)return'';const s=f.summary||{},ret=pct(s.retention),baseline=f.baseline||{},final=f.final||{};
  const cards=[['Velocidad alta',baseline.speedP95,final.speedP95,'km/h'],['Punta sprint',baseline.sprintPeakAvg,final.sprintPeakAvg,'km/h'],['Sprints / 10 min',baseline.sprintDensityPer10Min,final.sprintDensityPer10Min,''],['Recuperación',baseline.avgRecoveryS,final.avgRecoveryS,'s']];
  const rows=(f.windows||[]).map(w=>{const max=Math.max(1,Number(baseline.speedP95)||1),bar=Math.max(6,Math.min(100,Math.round((Number(w.speedP95)||0)/max*100)));return `<div style="display:grid;grid-template-columns:92px 1fr 72px 72px 72px;gap:9px;align-items:center;padding:8px 0;border-top:1px solid rgba(255,255,255,.06);font-size:10px"><span>${fmtClock(w.startSec)}–${fmtClock(w.endSec)}</span><div style="height:7px;border-radius:999px;background:#1d2821;overflow:hidden"><i style="display:block;width:${bar}%;height:100%;background:linear-gradient(90deg,#8d1f25,#e3262e)"></i></div><b>${fmt1(w.speedP95)} km/h</b><span>${fmt1(w.sprintDensityPer10Min)} spr.</span><span>${finite(w.avgRecoveryS)?Math.round(w.avgRecoveryS)+' s':'—'}</span></div>`}).join('');
  return `<section class="patx-gps-section patx-gps-wide"><div class="patx-gps-section-head"><span>RESPUESTA FÍSICA</span><h4>Intensidad durante los 60 minutos</h4></div><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:12px"><strong style="font-size:18px">${s.label||'Evolución de intensidad'}</strong>${ret!=null?`<span style="padding:5px 8px;border-radius:999px;background:#111a15;border:1px solid rgba(255,255,255,.08);font-size:10px">retención ${ret}%</span>`:''}</div><div class="patx-gps-inline-metrics">${cards.map(([label,a,b,u])=>`<div class="patx-gps-mini"><span>${label}</span><strong>${fmt1(a)}${u?' '+u:''} → ${fmt1(b)}${u?' '+u:''}</strong></div>`).join('')}</div><div style="margin-top:14px;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:0 10px 6px;background:#09100c"><div style="display:grid;grid-template-columns:92px 1fr 72px 72px 72px;gap:9px;padding:9px 0;color:#89958e;font-size:9px;font-weight:900;letter-spacing:.08em"><span>VENTANA</span><span>VELOCIDAD ALTA</span><span>P95</span><span>SPRINTS</span><span>RECUP.</span></div>${rows}</div>${s.notes?.length?`<ul class="patx-gps-notes">${s.notes.map(n=>`<li>${n}</li>`).join('')}</ul>`:''}<p class="patx-gps-note">Lectura continua con ventanas solapadas de aproximadamente 12 minutos, avanzando cada 5 minutos. Compara al jugador consigo mismo dentro de este partido; no usa primera/segunda parte ni compara jugadores.</p></section>`;
}
