-- Trivia question bank and admin-only CRUD RPCs.

create table if not exists public.trivia_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  answers jsonb not null,
  correct_index smallint not null,
  category text not null default 'Fútbol internacional',
  difficulty text not null default 'media',
  explanation text,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trivia_answers_array_check check (jsonb_typeof(answers)='array' and jsonb_array_length(answers)=4),
  constraint trivia_correct_index_check check (correct_index between 0 and 3),
  constraint trivia_difficulty_check check (difficulty in ('facil','media','dificil')),
  constraint trivia_question_length_check check (char_length(btrim(question)) between 4 and 500)
);
create index if not exists trivia_questions_active_idx on public.trivia_questions(active,category,id);
alter table public.trivia_questions enable row level security;
revoke all on public.trivia_questions from anon, authenticated;
grant all on public.trivia_questions to service_role;

create or replace function public.admin_list_trivia_questions()
returns table(id bigint,question text,answers jsonb,correct_index smallint,category text,difficulty text,explanation text,active boolean,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Solo el admin puede gestionar el trivial'; end if;
  return query select tq.id,tq.question,tq.answers,tq.correct_index,tq.category,tq.difficulty,tq.explanation,tq.active,tq.created_at,tq.updated_at from public.trivia_questions tq order by tq.active desc,tq.category,tq.id desc;
end; $$;

create or replace function public.admin_upsert_trivia_question(p_id bigint,p_question text,p_answers jsonb,p_correct_index smallint,p_category text,p_difficulty text,p_explanation text default null,p_active boolean default true)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
  if not public.is_admin() then raise exception 'Solo el admin puede gestionar el trivial'; end if;
  if char_length(btrim(coalesce(p_question,'')))<4 then raise exception 'Pregunta demasiado corta'; end if;
  if jsonb_typeof(p_answers)<>'array' or jsonb_array_length(p_answers)<>4 then raise exception 'Debe haber exactamente cuatro respuestas'; end if;
  if p_correct_index not between 0 and 3 then raise exception 'Respuesta correcta no válida'; end if;
  if p_difficulty not in ('facil','media','dificil') then raise exception 'Dificultad no válida'; end if;
  if p_id is null then
    insert into public.trivia_questions(question,answers,correct_index,category,difficulty,explanation,active,created_by)
    values(btrim(p_question),p_answers,p_correct_index,coalesce(nullif(btrim(p_category),''),'Fútbol internacional'),p_difficulty,nullif(btrim(coalesce(p_explanation,'')),''),coalesce(p_active,true),auth.uid()) returning id into v_id;
  else
    update public.trivia_questions set question=btrim(p_question),answers=p_answers,correct_index=p_correct_index,category=coalesce(nullif(btrim(p_category),''),'Fútbol internacional'),difficulty=p_difficulty,explanation=nullif(btrim(coalesce(p_explanation,'')),''),active=coalesce(p_active,true),updated_at=now() where id=p_id;
    if not found then raise exception 'Pregunta no encontrada'; end if;
    v_id:=p_id;
  end if;
  return v_id;
end; $$;

create or replace function public.admin_delete_trivia_question(p_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Solo el admin puede gestionar el trivial'; end if;
  delete from public.trivia_questions where id=p_id;
  return found;
end; $$;

revoke all on function public.admin_list_trivia_questions() from public,anon;
revoke all on function public.admin_upsert_trivia_question(bigint,text,jsonb,smallint,text,text,text,boolean) from public,anon;
revoke all on function public.admin_delete_trivia_question(bigint) from public,anon;
grant execute on function public.admin_list_trivia_questions() to authenticated;
grant execute on function public.admin_upsert_trivia_question(bigint,text,jsonb,smallint,text,text,text,boolean) to authenticated;
grant execute on function public.admin_delete_trivia_question(bigint) to authenticated;

insert into public.game_definitions(id,name,description,category,scoring_direction,unit,default_attempts,config,active,sort_order)
values('football-trivia','Trivial futbolero','Cinco preguntas de fútbol. Acertar rápido da más puntos.','football','higher','points',2,'{"questions":5,"question_timeout_ms":8000,"max_score":5000}'::jsonb,false,140)
on conflict(id) do update set name=excluded.name,description=excluded.description,category=excluded.category,scoring_direction=excluded.scoring_direction,unit=excluded.unit,default_attempts=excluded.default_attempts,config=excluded.config,sort_order=excluded.sort_order,updated_at=now();

-- Seed examples only if the question bank is empty.
insert into public.trivia_questions(question,answers,correct_index,category,difficulty,explanation,active)
select * from (values
('¿Qué selección ganó el Mundial de 2010?', '["España","Alemania","Países Bajos","Brasil"]'::jsonb, 0::smallint, 'Mundiales','facil','España ganó el Mundial de Sudáfrica 2010.',true),
('¿Quién marcó el gol de la final del Mundial de 2010?', '["David Villa","Xavi Hernández","Andrés Iniesta","Fernando Torres"]'::jsonb, 2::smallint, 'Mundiales','facil','Andrés Iniesta marcó en la prórroga ante Países Bajos.',true),
('¿Qué selección ganó el Mundial de 2022?', '["Francia","Argentina","Croacia","Brasil"]'::jsonb, 1::smallint, 'Mundiales','facil','Argentina ganó la final frente a Francia.',true),
('¿Quién protagonizó el famoso gol conocido como La Mano de Dios?', '["Pelé","Diego Maradona","Johan Cruyff","Zinedine Zidane"]'::jsonb, 1::smallint, 'Historia','facil','Maradona lo marcó ante Inglaterra en el Mundial de 1986.',true),
('¿Cuántos jugadores tiene cada equipo sobre el campo al inicio de un partido de fútbol 11?', '["9","10","11","12"]'::jsonb, 2::smallint, 'Reglamento','facil','Cada equipo inicia con once jugadores, incluido el portero.',true),
('¿A qué distancia de la línea de gol está el punto de penalti?', '["9 metros","10 metros","11 metros","12 metros"]'::jsonb, 2::smallint, 'Reglamento','media','El punto de penalti está a 11 metros de la línea de gol.',true),
('¿Quién era el seleccionador de España en el Mundial de 2010?', '["Luis Aragonés","Vicente del Bosque","Javier Clemente","Julen Lopetegui"]'::jsonb, 1::smallint, 'Selección española','media','Vicente del Bosque dirigió a España en Sudáfrica 2010.',true),
('¿Qué selección ganó el Mundial de 2014?', '["Argentina","Alemania","Italia","España"]'::jsonb, 1::smallint, 'Mundiales','facil','Alemania derrotó a Argentina en la final de 2014.',true),
('¿Qué selección ganó el Mundial de 2006?', '["Francia","Brasil","Italia","Alemania"]'::jsonb, 2::smallint, 'Mundiales','media','Italia venció a Francia en la tanda de penaltis.',true),
('¿Cómo se conocía históricamente a la actual UEFA Champions League?', '["Copa de Europa","Copa Latina","Copa de Ferias","Recopa"]'::jsonb, 0::smallint, 'Champions','media','La competición nació como Copa de Europa.',true)
) as seed(question,answers,correct_index,category,difficulty,explanation,active)
where not exists(select 1 from public.trivia_questions);
