-- Self-service account registration requested by a player.
-- The public flow is handled by the account-auth Edge Function.
-- Client roles are explicitly denied direct access to registration/login audit tables.

alter table public.profiles
  add column if not exists credential_scheme text not null default 'native';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_credential_scheme_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_credential_scheme_check
      check (credential_scheme in ('native','patx_v1'));
  end if;
end $$;

-- One Patxanguilles player can belong to only one Auth account.
create unique index if not exists profiles_player_id_unique
  on public.profiles(player_id)
  where player_id is not null;

create table if not exists public.player_registration_requests (
  id uuid primary key default gen_random_uuid(),
  player_id bigint not null references public.players(id) on delete cascade,
  code_hash text not null,
  requester_hash text,
  status text not null default 'pending',
  code_attempts integer not null default 0,
  expires_at timestamptz not null,
  telegram_sent_at timestamptz,
  auth_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint player_registration_requests_status_check
    check (status in ('pending','completed','cancelled','expired')),
  constraint player_registration_requests_attempts_check
    check (code_attempts >= 0 and code_attempts <= 20)
);

create index if not exists player_registration_requests_player_idx
  on public.player_registration_requests(player_id, created_at desc);
create index if not exists player_registration_requests_pending_idx
  on public.player_registration_requests(player_id, expires_at)
  where status = 'pending';
create index if not exists player_registration_requests_requester_idx
  on public.player_registration_requests(requester_hash, created_at desc);

alter table public.player_registration_requests enable row level security;
drop policy if exists "Registro interno sin acceso cliente" on public.player_registration_requests;
create policy "Registro interno sin acceso cliente"
  on public.player_registration_requests
  for all
  to anon, authenticated
  using (false)
  with check (false);
revoke all on public.player_registration_requests from anon, authenticated;
grant all on public.player_registration_requests to service_role;

-- Login throttling is intentionally server-only. Password strength is not
-- enforced in the UI, so failed attempts must be rate-limited instead.
create table if not exists public.account_login_attempts (
  id bigint generated by default as identity primary key,
  player_id bigint references public.players(id) on delete cascade,
  requester_hash text,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists account_login_attempts_player_idx
  on public.account_login_attempts(player_id, attempted_at desc);
create index if not exists account_login_attempts_requester_idx
  on public.account_login_attempts(requester_hash, attempted_at desc);

alter table public.account_login_attempts enable row level security;
drop policy if exists "Login interno sin acceso cliente" on public.account_login_attempts;
create policy "Login interno sin acceso cliente"
  on public.account_login_attempts
  for all
  to anon, authenticated
  using (false)
  with check (false);
revoke all on public.account_login_attempts from anon, authenticated;
grant all on public.account_login_attempts to service_role;
